name: Python Script Runner

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 */4 * * *'  # Run every day at 9 a.m.

jobs:
  run_script:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      env:
        CONSUMER_API_KEY: ${{ secrets.CONSUMER_API_KEY }}
        CONSUMER_API_SECRET: ${{ secrets.CONSUMER_API_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python main.py