name: Python Script Runner

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 9 * * *'  # Run every day at 9 a.m.

jobs:
  run_script:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      env:
        ACCESS_KEY: ${{ secrets.CONSUMER_KEY }}
        ACCESS_SECRET: ${{ secrets.CONSUMER_SECRET }}
        USER_KEY: ${{ secrets.ACCESS_TOKEN }}
        USER_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      run: python blogic.py
